
import { Equipment, InfrastructureItem } from './types';

export const DC_EQUIPMENT: Equipment[] = [
  { 
    id: '1', name: 'Server Load Balancer', area: 'Network', type: 'SLB', vendor: 'Array', model: 'AVX 7900', qty: 2, sopStatus: 'Available',
    email: 'tacsupport@arraynetworks.net', phone: '1800 572 7729', licenseApplicable: 'Yes', 
    contactInfo: 'Mr. Vishal Lokhade', contactNumber: '8169172597',
    attachments: []
  },
  { 
    id: '2', name: 'Web Application Firewall', area: 'Security', type: 'WAF', vendor: 'Array', model: 'AVX 7900', qty: 2, sopStatus: 'Available',
    email: 'tacsupport@arraynetworks.net', phone: '1800 572 7729', licenseApplicable: 'Yes',
    attachments: []
  },
  { 
    id: '9', name: 'Primary & Secondary Firewall', area: 'Security', type: 'Firewall', vendor: 'FortiNet', model: 'FortiGate-1001F', qty: 2, sopStatus: 'Available',
    email: 'cs@fortinet.com', phone: '0008000503635', licenseApplicable: 'Yes', webSupport: 'https://support.fortinet.com',
    userName: 'fsl.network@starnextinnovations.com', credentials: 'DFSL@2025mh@#', otpRequired: 'Yes (on Email / Mr. Prayag)',
    validity: '08-Jul-30',
    attachments: []
  },
  { 
    id: '17', name: 'POE Switch', area: 'Network', type: 'Switch', vendor: 'Netgear', model: 'GS724TPv3', qty: 57, sopStatus: 'Available',
    email: 'support@netgearstore.in', phone: '1800 419 4543', licenseApplicable: 'No', 
    webSupport: 'https://accounts2.netgear.com/login', validity: '12-Oct-26', contactInfo: 'Mr. Devendra', contactNumber: '+91 95520 10788',
    attachments: []
  },
  { 
    id: '20', name: 'Blade Server', area: 'Comput', type: 'Server', vendor: 'Dell', model: 'PowerEdge MX750c', qty: 19, sopStatus: 'Available',
    licenseApplicable: 'No', webSupport: 'https://www.dell.com/support/home/en-in', validity: '14-May-30', contactNumber: '7795889140',
    attachments: []
  },
  { 
    id: '23', name: 'Unified Storage', area: 'Comput', type: 'Storage', vendor: 'NetApp', model: 'FAS 8700', qty: 17, sopStatus: 'Available',
    email: 'Support@netapp.com', phone: '8001008948', licenseApplicable: 'No', webSupport: 'https://mysupport.netapp.com',
    validity: '14-May-30',
    attachments: []
  },
  { 
    id: '26', name: 'Server Virtualization', area: 'Application', type: 'Virtualization', vendor: 'broadcom', model: 'EsXi 8.03e', qty: 'N/A', sopStatus: 'Available',
    email: 'support@broadcom.com', phone: '8040440000', licenseApplicable: 'Yes', webSupport: 'https://access.broadcom.com',
    validity: 'Pending OEM Response', contactInfo: 'Mr. Ajay', contactNumber: '9881224148',
    attachments: []
  }
];

export const INFRA_ITEMS: InfrastructureItem[] = [
  // Ratnagiri
  { id: 'rat-1', location: 'Ratnagiri', category: 'Router', hostname: 'FSL-BR-RAT-COR-RTR-01', ipAddress: '10.4.85.11', description: 'Ratnagiri - Primary Router' },
  { id: 'rat-2', location: 'Ratnagiri', category: 'Router', hostname: 'FSL-BR-RAT-COR-RTR-02', ipAddress: '10.4.85.12', description: 'Ratnagiri - Secondary Router' },
  { id: 'rat-3', location: 'Ratnagiri', category: 'Firewall', hostname: 'FSL-BR-RAT-FGT-FW-01', ipAddress: '10.4.85.1', description: 'Ratnagiri - Firewall' },
  { id: 'rat-4', location: 'Ratnagiri', category: 'Firewall', hostname: 'FSL-BR-RAT-FGT-FW-02', ipAddress: '', description: 'Ratnagiri - Firewall' },
  { id: 'rat-5', location: 'Ratnagiri', category: 'Switch', hostname: 'FSL-BR-RAT-AGG-R1-SW01', ipAddress: '10.4.85.15', description: 'Ratnagiri - Switch' },
  { id: 'rat-6', location: 'Ratnagiri', category: 'Switch', hostname: 'FSL-BR-RAT-AGG-R2-SW01', ipAddress: '10.4.85.16', description: 'Ratnagiri - Switch' },
  { id: 'rat-7', location: 'Ratnagiri', category: 'Switch', hostname: 'FSL-BR-RAT-FRS-R1-SW01', ipAddress: '10.4.85.17', description: 'Ratnagiri - Switch' },
  { id: 'rat-8', location: 'Ratnagiri', category: 'PoE Switch', hostname: 'FSL-BR-RAT-FRS-R1-POE-SW01', ipAddress: '10.4.85.18', description: 'Ratnagiri - PoE Switch' },
  { id: 'rat-9', location: 'Ratnagiri', category: 'PoE Switch', hostname: 'FSL-BR-RAT-SEC-R1-POE-SW01', ipAddress: '10.4.85.19', description: 'Ratnagiri - PoE Switch' },

  // Nashik
  { id: 'nsk-1', location: 'Nashik', category: 'Router', hostname: 'FSL-BR-NSK-COR-RTR-01', ipAddress: '10.2.213.11', description: 'Nashik - Primary Router' },
  { id: 'nsk-2', location: 'Nashik', category: 'Router', hostname: 'FSL-BR-NSK-COR-RTR-02', ipAddress: '10.2.213.12', description: 'Nashik - Secondary Router' },
  { id: 'nsk-3', location: 'Nashik', category: 'Firewall', hostname: 'FSL-BR-NSK-FGT-FW-01', ipAddress: '10.2.213.1', description: 'Nashik - Firewall' },
  { id: 'nsk-4', location: 'Nashik', category: 'Firewall', hostname: 'FSL-BR-NSK-FGT-FW-02', ipAddress: '', description: 'Nashik - Firewall' },
  { id: 'nsk-5', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-AGG-R1-SW01', ipAddress: '10.2.213.15', description: 'Nashik - Switch' },
  { id: 'nsk-6', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-AGG-R2-SW01', ipAddress: '10.2.213.16', description: 'Nashik - Switch' },
  { id: 'nsk-7', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-AGG-R1-SW02', ipAddress: '10.2.213.17', description: 'Nashik - Switch' },
  { id: 'nsk-8', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-AGG-R2-SW02', ipAddress: '10.2.213.18', description: 'Nashik - Switch' },
  { id: 'nsk-9', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-GRD-R1-SW01', ipAddress: '10.2.213.19', description: 'Nashik - Switch' },
  { id: 'nsk-10', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-GRD-R1-SW02', ipAddress: '10.2.213.20', description: 'Nashik - Switch' },
  { id: 'nsk-11', location: 'Nashik', category: 'PoE Switch', hostname: 'FSL-BR-NSK-GRD-R1-POE-SW01', ipAddress: '10.2.213.21', description: 'Nashik - PoE Switch' },
  { id: 'nsk-12', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-GRD-R2-SW01', ipAddress: '10.2.213.22', description: 'Nashik - Switch' },
  { id: 'nsk-13', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-GRD-R2-SW02', ipAddress: '10.2.213.23', description: 'Nashik - Switch' },
  { id: 'nsk-14', location: 'Nashik', category: 'PoE Switch', hostname: 'FSL-BR-NSK-GRD-R2-POE-SW01', ipAddress: '10.2.213.24', description: 'Nashik - PoE Switch' },
  { id: 'nsk-15', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-FRS-R1-SW01', ipAddress: '10.2.213.25', description: 'Nashik - Switch' },
  { id: 'nsk-16', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-FRS-R1-SW02', ipAddress: '10.2.213.26', description: 'Nashik - Switch' },
  { id: 'nsk-17', location: 'Nashik', category: 'PoE Switch', hostname: 'FSL-BR-NSK-FRS-R1-POE-SW01', ipAddress: '10.2.213.27', description: 'Nashik - PoE Switch' },
  { id: 'nsk-18', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-FRS-R2-SW01', ipAddress: '10.2.213.28', description: 'Nashik - Switch' },
  { id: 'nsk-19', location: 'Nashik', category: 'Switch', hostname: 'FSL-BR-NSK-FRS-R2-SW02', ipAddress: '10.2.213.29', description: 'Nashik - Switch' },
  { id: 'nsk-20', location: 'Nashik', category: 'PoE Switch', hostname: 'FSL-BR-NSK-FRS-R2-POE-SW01', ipAddress: '10.2.213.30', description: 'Nashik - PoE Switch' },

  // Nanded
  { id: 'nad-1', location: 'Nanded', category: 'Router', hostname: 'FSL-BR-NAD-COR-RTR-01', ipAddress: '10.3.149.11', description: 'Nanded - Primary Router' },
  { id: 'nad-2', location: 'Nanded', category: 'Router', hostname: 'FSL-BR-NAD-COR-RTR-02', ipAddress: '10.3.149.12', description: 'Nanded - Secondary Router' },
  { id: 'nad-3', location: 'Nanded', category: 'Firewall', hostname: 'FSL-BR-NAD-FGT-FW-01', ipAddress: '10.3.149.1', description: 'Nanded - Firewall' },
  { id: 'nad-4', location: 'Nanded', category: 'Firewall', hostname: 'FSL-BR-NAD-FGT-FW-02', ipAddress: '', description: 'Nanded - Firewall' },
  { id: 'nad-5', location: 'Nanded', category: 'Switch', hostname: 'FSL-BR-NAD-AGG-R1-SW01', ipAddress: '10.3.149.15', description: 'Nanded - Switch' },
  { id: 'nad-6', location: 'Nanded', category: 'Switch', hostname: 'FSL-BR-NAD-AGG-R2-SW01', ipAddress: '10.3.149.16', description: 'Nanded - Switch' },
  { id: 'nad-7', location: 'Nanded', category: 'Switch', hostname: 'FSL-BR-NAD-SEC-R1-SW01', ipAddress: '10.3.149.17', description: 'Nanded - Switch' },
  { id: 'nad-8', location: 'Nanded', category: 'Switch', hostname: 'FSL-BR-NAD-SEC-R1-SW02', ipAddress: '10.3.149.18', description: 'Nanded - Switch' },
  { id: 'nad-9', location: 'Nanded', category: 'PoE Switch', hostname: 'FSL-BR-NAD-SEC-R1-POE-SW01', ipAddress: '10.3.149.19', description: 'Nanded - PoE Switch' },
  { id: 'nad-10', location: 'Nanded', category: 'Switch', hostname: 'FSL-BR-NAD-SEC-R2-SW01', ipAddress: '10.3.149.20', description: 'Nanded - Switch' },
  { id: 'nad-11', location: 'Nanded', category: 'PoE Switch', hostname: 'FSL-BR-NAD-SEC-R2-POE-SW01', ipAddress: '10.3.149.21', description: 'Nanded - PoE Switch' },
  { id: 'nad-12', location: 'Nanded', category: 'Switch', hostname: 'FSL-BR-NAD-SEC-R3-SW01', ipAddress: '10.3.149.22', description: 'Nanded - Switch' },
  { id: 'nad-13', location: 'Nanded', category: 'PoE Switch', hostname: 'FSL-BR-NAD-SEC-R3-POE-SW01', ipAddress: '10.3.149.23', description: 'Nanded - PoE Switch' },

  // Nagpur
  { id: 'nag-1', location: 'Nagpur', category: 'Router', hostname: 'FSL-BR-NAG-COR-RTR-01', ipAddress: '10.2.149.11', description: 'Nagpur - Primary Router' },
  { id: 'nag-2', location: 'Nagpur', category: 'Router', hostname: 'FSL-BR-NAG-COR-RTR-02', ipAddress: '10.2.149.12', description: 'Nagpur - Secondary Router' },
  { id: 'nag-3', location: 'Nagpur', category: 'Firewall', hostname: 'FSL-BR-NAG-FGT-FW-01', ipAddress: '10.2.149.1', description: 'Nagpur - Firewall' },
  { id: 'nag-4', location: 'Nagpur', category: 'Firewall', hostname: 'FSL-BR-NAG-FGT-FW-02', ipAddress: '', description: 'Nagpur - Firewall' },
  { id: 'nag-5', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-AGG-R1-SW01', ipAddress: '10.2.149.15', description: 'Nagpur - Switch' },
  { id: 'nag-6', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-AGG-R2-SW01', ipAddress: '10.2.149.16', description: 'Nagpur - Switch' },
  { id: 'nag-7', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-AGG-R1-SW02', ipAddress: '10.2.149.17', description: 'Nagpur - Switch' },
  { id: 'nag-8', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-AGG-R2-SW02', ipAddress: '10.2.149.18', description: 'Nagpur - Switch' },
  { id: 'nag-9', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-GRD-R1-SW01', ipAddress: '10.2.149.19', description: 'Nagpur - Switch' },
  { id: 'nag-10', location: 'Nagpur', category: 'PoE Switch', hostname: 'FSL-BR-NAG-GRD-R1-POE-SW01', ipAddress: '10.2.149.20', description: 'Nagpur - PoE Switch' },
  { id: 'nag-11', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-GRD-R2-SW01', ipAddress: '10.2.149.21', description: 'Nagpur - Switch' },
  { id: 'nag-12', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-GRD-R2-SW02', ipAddress: '10.2.149.22', description: 'Nagpur - Switch' },
  { id: 'nag-13', location: 'Nagpur', category: 'PoE Switch', hostname: 'FSL-BR-NAG-GRD-R2-POE-SW01', ipAddress: '10.2.149.23', description: 'Nagpur - PoE Switch' },
  { id: 'nag-14', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-FST-R1-SW01', ipAddress: '10.2.149.24', description: 'Nagpur - Switch' },
  { id: 'nag-15', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-FST-R1-SW02', ipAddress: '10.2.149.25', description: 'Nagpur - Switch' },
  { id: 'nag-16', location: 'Nagpur', category: 'PoE Switch', hostname: 'FSL-BR-NAG-FST-R1-POE-SW01', ipAddress: '10.2.149.26', description: 'Nagpur - PoE Switch' },
  { id: 'nag-17', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NGP-FST-R2-SW01', ipAddress: '10.2.149.27', description: 'Nagpur - Switch' },
  { id: 'nag-18', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NGP-FST-R2-SW02', ipAddress: '10.2.149.28', description: 'Nagpur - Switch' },
  { id: 'nag-19', location: 'Nagpur', category: 'PoE Switch', hostname: 'FSL-BR-NAG-FST-R2-POE-SW01', ipAddress: '10.2.149.29', description: 'Nagpur - PoE Switch' },
  { id: 'nag-20', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-SEC-R1-SW01', ipAddress: '10.2.149.30', description: 'Nagpur - Switch' },
  { id: 'nag-21', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-SEC-R1-SW02', ipAddress: '10.2.149.31', description: 'Nagpur - Switch' },
  { id: 'nag-22', location: 'Nagpur', category: 'Switch', hostname: 'FSL-BR-NAG-SEC-R1-SW03', ipAddress: '10.2.149.32', description: 'Nagpur - Switch' },
  { id: 'nag-23', location: 'Nagpur', category: 'PoE Switch', hostname: 'FSL-BR-NAG-SEC-R1-POE-SW01', ipAddress: '10.2.149.33', description: 'Nagpur - PoE Switch' },
  { id: 'nag-24', location: 'Nagpur', category: 'PoE Switch', hostname: 'FSL-BR-NAG-SEC-SER-POE-SW01', ipAddress: '10.2.149.34', description: 'Nagpur - PoE Switch' },

  // Kolhapur
  { id: 'kol-1', location: 'Kolhapur', category: 'Router', hostname: 'FSL-BR-KOL-COR-RTR-01', ipAddress: '10.3.213.11', description: 'Kolhapur - Primary Router' },
  { id: 'kol-2', location: 'Kolhapur', category: 'Router', hostname: 'FSL-BR-KOL-COR-RTR-02', ipAddress: '10.3.213.12', description: 'Kolhapur - Secondary Router' },
  { id: 'kol-3', location: 'Kolhapur', category: 'Firewall', hostname: 'FSL-BR-KOL-FGT-FW-01', ipAddress: '10.3.213.1', description: 'Kolhapur - Firewall' },
  { id: 'kol-4', location: 'Kolhapur', category: 'Firewall', hostname: 'FSL-BR-KOL-FGT-FW-02', ipAddress: '', description: 'Kolhapur - Firewall' },
  { id: 'kol-5', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-AGG-R1-SW01', ipAddress: '10.3.213.15', description: 'Kolhapur - Switch' },
  { id: 'kol-6', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-AGG-R2-SW01', ipAddress: '10.3.213.16', description: 'Kolhapur - Switch' },
  { id: 'kol-7', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-AGG-R1-SW02', ipAddress: '10.3.213.17', description: 'Kolhapur - Switch' },
  { id: 'kol-8', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-AGG-R2-SW02', ipAddress: '10.3.213.18', description: 'Kolhapur - Switch' },
  { id: 'kol-9', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-FST-R1-SW01', ipAddress: '10.3.213.19', description: 'Kolhapur - Switch' },
  { id: 'kol-10', location: 'Kolhapur', category: 'PoE Switch', hostname: 'FSL-BR-KOL-FST-R1-POE-SW01', ipAddress: '10.3.213.20', description: 'Kolhapur - PoE Switch' },
  { id: 'kol-11', location: 'Kolhapur', category: 'PoE Switch', hostname: 'FSL-BR-KOL-FST-R1-POE-SW02', ipAddress: '10.3.213.21', description: 'Kolhapur - PoE Switch' },
  { id: 'kol-12', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-SEC-R1-SW01', ipAddress: '10.3.213.22', description: 'Kolhapur - Switch' },
  { id: 'kol-13', location: 'Kolhapur', category: 'PoE Switch', hostname: 'FSL-BR-KOL-SEC-R1-POE-SW01', ipAddress: '10.3.213.23', description: 'Kolhapur - PoE Switch' },
  { id: 'kol-14', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-TRD-R1-SW01', ipAddress: '10.3.213.24', description: 'Kolhapur - Switch' },
  { id: 'kol-15', location: 'Kolhapur', category: 'PoE Switch', hostname: 'FSL-BR-KOL-TRD-R1-POE-SW01', ipAddress: '10.3.213.25', description: 'Kolhapur - PoE Switch' },
  { id: 'kol-16', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-FOUTH-R1-SW01', ipAddress: '10.3.213.26', description: 'Kolhapur - Switch' },
  { id: 'kol-17', location: 'Kolhapur', category: 'Switch', hostname: 'FSL-BR-KOL-FOUTH-R1-SW02', ipAddress: '10.3.213.29', description: 'Kolhapur - Switch' },
  { id: 'kol-18', location: 'Kolhapur', category: 'PoE Switch', hostname: 'FSL-BR-KOL-FOUTH-R1-POE-SW01', ipAddress: '10.3.213.27', description: 'Kolhapur - PoE Switch' },
  { id: 'kol-19', location: 'Kolhapur', category: 'PoE Switch', hostname: 'FSL-BR-KOL-FOUTH-R1-POE-SW02', ipAddress: '10.3.213.28', description: 'Kolhapur - PoE Switch' },

  // Dhule
  { id: 'dhu-1', location: 'Dhule', category: 'Router', hostname: 'FSL-BR-DHU-COR-RTR-01', ipAddress: '10.5.21.11', description: 'Dhule - Primary Router' },
  { id: 'dhu-2', location: 'Dhule', category: 'Router', hostname: 'FSL-BR-DHU-COR-RTR-02', ipAddress: '10.5.21.12', description: 'Dhule - Secondary Router' },
  { id: 'dhu-3', location: 'Dhule', category: 'Firewall', hostname: 'FSL-BR-DHU-FGT-FW-01', ipAddress: '10.5.21.1', description: 'Dhule - Firewall' },
  { id: 'dhu-4', location: 'Dhule', category: 'Firewall', hostname: 'FSL-BR-DHU-FGT-FW-02', ipAddress: '', description: 'Dhule - Firewall' },
  { id: 'dhu-5', location: 'Dhule', category: 'Switch', hostname: 'FSL-BR-DHU-AGG-R1-SW01', ipAddress: '10.5.21.15', description: 'Dhule - Switch' },
  { id: 'dhu-6', location: 'Dhule', category: 'Switch', hostname: 'FSL-BR-DHU-AGG-R2-SW01', ipAddress: '10.5.21.16', description: 'Dhule - Switch' },
  { id: 'dhu-7', location: 'Dhule', category: 'Switch', hostname: 'FSL-BR-DHU-GRD-R1-SW01', ipAddress: '10.5.21.17', description: 'Dhule - Switch' },
  { id: 'dhu-8', location: 'Dhule', category: 'PoE Switch', hostname: 'FSL-BR-DHU-GRD-R1-POE-SW01', ipAddress: '10.5.21.18', description: 'Dhule - PoE Switch' },
  { id: 'dhu-9', location: 'Dhule', category: 'PoE Switch', hostname: 'FSL-BR-DHU-GRD-R1-POE-SW02', ipAddress: '10.5.21.19', description: 'Dhule - PoE Switch' },

  // Chandrapur
  { id: 'chnd-1', location: 'Chandrapur', category: 'Router', hostname: 'FSL-BR-CHND-COR-RTR-01', ipAddress: '10.4.213.11', description: 'Chandrapur - Primary Router' },
  { id: 'chnd-2', location: 'Chandrapur', category: 'Router', hostname: 'FSL-BR-CHND-COR-RTR-02', ipAddress: '10.4.213.12', description: 'Chandrapur - Secondary Router' },
  { id: 'chnd-3', location: 'Chandrapur', category: 'Firewall', hostname: 'FSL-BR-CHND-FGT-FW-01', ipAddress: '10.4.213.1', description: 'Chandrapur - Firewall' },
  { id: 'chnd-4', location: 'Chandrapur', category: 'Firewall', hostname: 'FSL-BR-CHND-FGT-FW-02', ipAddress: '', description: 'Chandrapur - Firewall' },
  { id: 'chnd-5', location: 'Chandrapur', category: 'Switch', hostname: 'FSL-BR-CHND-AGG-R1-SW01', ipAddress: '10.4.213.15', description: 'Chandrapur - Switch' },
  { id: 'chnd-6', location: 'Chandrapur', category: 'Switch', hostname: 'FSL-BR-CHND-AGG-R2-SW01', ipAddress: '10.4.213.16', description: 'Chandrapur - Switch' },
  { id: 'chnd-7', location: 'Chandrapur', category: 'Switch', hostname: 'FSL-BR-CHD-FRS-R1-SW01', ipAddress: '10.4.213.19', description: 'Chandrapur - Switch' },
  { id: 'chnd-8', location: 'Chandrapur', category: 'PoE Switch', hostname: 'FSL-BR-CHD-FRS-R1-POE', ipAddress: '10.4.213.20', description: 'Chandrapur - PoE Switch' },
  { id: 'chnd-9', location: 'Chandrapur', category: 'Switch', hostname: 'FSL-BR-CHD-THD-R1-SW01', ipAddress: '10.4.213.21', description: 'Chandrapur - Switch' },
  { id: 'chnd-10', location: 'Chandrapur', category: 'PoE Switch', hostname: 'FSL-BR-CHD-THD-R1-POE', ipAddress: '10.4.213.22', description: 'Chandrapur - PoE Switch' },

  // Sambhaji Nagar
  { id: 'aur-1', location: 'Sambhaji Nagar', category: 'Router', hostname: 'FSL-BR-AUR-COR-RTR-01', ipAddress: '10.3.21.11', description: 'Sambhaji Nagar - Primary Router' },
  { id: 'aur-2', location: 'Sambhaji Nagar', category: 'Router', hostname: 'FSL-BR-AUR-COR-RTR-02', ipAddress: '10.3.21.12', description: 'Sambhaji Nagar - Secondary Router' },
  { id: 'aur-3', location: 'Sambhaji Nagar', category: 'Firewall', hostname: 'FSL-BR-AUR-FGT-FW-01', ipAddress: '10.3.21.1', description: 'Sambhaji Nagar - Firewall' },
  { id: 'aur-4', location: 'Sambhaji Nagar', category: 'Firewall', hostname: 'FSL-BR-AUR-FGT-FW-02', ipAddress: '', description: 'Sambhaji Nagar - Firewall' },
  { id: 'aur-5', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-AGG-R1-SW01', ipAddress: '10.3.21.15', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-6', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-AGG-R2-SW01', ipAddress: '10.3.21.16', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-7', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-AGG-R1-SW02', ipAddress: '10.3.21.17', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-8', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-AGG-R2-SW02', ipAddress: '10.3.21.18', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-9', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-GRD-B1R1-SW01', ipAddress: '10.3.21.19', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-10', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-GRD-B1R1-SW02', ipAddress: '10.3.21.20', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-11', location: 'Sambhaji Nagar', category: 'PoE Switch', hostname: 'FSL-BR-AUR-GRD-B1R1-POE-SW01', ipAddress: '10.3.21.21', description: 'Sambhaji Nagar - PoE Switch' },
  { id: 'aur-12', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-FRS-B1R1-SW01', ipAddress: '10.3.21.22', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-13', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-FRS-B1R1-SW02', ipAddress: '10.3.21.23', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-14', location: 'Sambhaji Nagar', category: 'PoE Switch', hostname: 'FSL-BR-AUR-FRS-B1R1-POE-SW01', ipAddress: '10.3.21.24', description: 'Sambhaji Nagar - PoE Switch' },
  { id: 'aur-15', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-SEC-B1R1-SW01', ipAddress: '10.3.21.25', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-16', location: 'Sambhaji Nagar', category: 'PoE Switch', hostname: 'FSL-BR-AUR-SEC-B1R1-POE-SW01', ipAddress: '10.3.21.26', description: 'Sambhaji Nagar - PoE Switch' },
  { id: 'aur-17', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-GRD-B2R1-SW01', ipAddress: '10.3.21.27', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-18', location: 'Sambhaji Nagar', category: 'PoE Switch', hostname: 'FSL-BR-AUR-GRD-B2R1-POE-SW01', ipAddress: '10.3.21.28', description: 'Sambhaji Nagar - PoE Switch' },
  { id: 'aur-19', location: 'Sambhaji Nagar', category: 'Switch', hostname: 'FSL-BR-AUR-FRS-B2R1-SW01', ipAddress: '10.3.21.29', description: 'Sambhaji Nagar - Switch' },
  { id: 'aur-20', location: 'Sambhaji Nagar', category: 'PoE Switch', hostname: 'FSL-BR-AUR-FRS-B2R1-POE-SW01', ipAddress: '10.3.21.30', description: 'Sambhaji Nagar - PoE Switch' },

  // Amravati
  { id: 'amr-1', location: 'Amravati', category: 'Router', hostname: 'FSL-BR-AMR-COR-RTR-01', ipAddress: '10.3.85.11', description: 'Amravati - Primary Router' },
  { id: 'amr-2', location: 'Amravati', category: 'Router', hostname: 'FSL-BR-AMR-COR-RTR-02', ipAddress: '10.3.85.12', description: 'Amravati - Secondary Router' },
  { id: 'amr-3', location: 'Amravati', category: 'Firewall', hostname: 'FSL-BR-AMR-FGT-FW-01', ipAddress: '10.3.85.1', description: 'Amravati - Firewall' },
  { id: 'amr-4', location: 'Amravati', category: 'Firewall', hostname: 'FSL-BR-AMR-FGT-FW-02', ipAddress: '', description: 'Amravati - Firewall' },
  { id: 'amr-5', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-AGG-R1-SW01', ipAddress: '10.3.85.15', description: 'Amravati - Switch' },
  { id: 'amr-6', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-AGG-R2-SW01', ipAddress: '10.3.85.16', description: 'Amravati - Switch' },
  { id: 'amr-7', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-AGG-R1-SW02', ipAddress: '10.3.85.17', description: 'Amravati - Switch' },
  { id: 'amr-8', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-AGG-R2-SW02', ipAddress: '10.3.85.18', description: 'Amravati - Switch' },
  { id: 'amr-9', location: 'Amravati', category: 'PoE Switch', hostname: 'FSL-BR-AMR-GRD-R1-SW01', ipAddress: '10.3.85.27', description: 'Amravati - PoE Switch' },
  { id: 'amr-10', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-FRS-R1-SW01', ipAddress: '10.3.85.19', description: 'Amravati - Switch' },
  { id: 'amr-11', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-FRS-R1-SW02', ipAddress: '10.3.85.20', description: 'Amravati - Switch' },
  { id: 'amr-12', location: 'Amravati', category: 'PoE Switch', hostname: 'FSL-BR-AMR-FRS-R1-POE-SW01', ipAddress: '10.3.85.21', description: 'Amravati - PoE Switch' },
  { id: 'amr-13', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-SEC-R1-SW01', ipAddress: '10.3.85.22', description: 'Amravati - Switch' },
  { id: 'amr-14', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-SEC-R1-SW02', ipAddress: '10.3.85.26', description: 'Amravati - Switch' },
  { id: 'amr-15', location: 'Amravati', category: 'PoE Switch', hostname: 'FSL-BR-AMR-SEC-R1-POE-SW01', ipAddress: '10.3.85.23', description: 'Amravati - PoE Switch' },
  { id: 'amr-16', location: 'Amravati', category: 'Switch', hostname: 'FSL-BR-AMR-TRD-R1-SW01', ipAddress: '10.3.85.24', description: 'Amravati - Switch' },
  { id: 'amr-17', location: 'Amravati', category: 'PoE Switch', hostname: 'FSL-BR-AMR-TRD-R1-POE-SW01', ipAddress: '10.3.85.25', description: 'Amravati - PoE Switch' },

  // Thane
  { id: 'tha-1', location: 'Thane', category: 'Router', hostname: 'FSL-BR-THA-COR-RTR-01', ipAddress: '10.4.21.11', description: 'Thane - Primary Router' },
  { id: 'tha-2', location: 'Thane', category: 'Router', hostname: 'FSL-BR-THA-COR-RTR-02', ipAddress: '10.4.21.12', description: 'Thane - Secondary Router' },
  { id: 'tha-3', location: 'Thane', category: 'Firewall', hostname: 'FSL-BR-THA-FGT-FW-01', ipAddress: '10.4.21.1', description: 'Thane - Firewall' },
  { id: 'tha-4', location: 'Thane', category: 'Firewall', hostname: 'FSL-BR-THA-FGT-FW-02', ipAddress: '', description: 'Thane - Firewall' },
  { id: 'tha-5', location: 'Thane', category: 'Switch', hostname: 'FSL-BR-THA-AGG-R1-SW01', ipAddress: '10.4.21.15', description: 'Thane - Switch' },
  { id: 'tha-6', location: 'Thane', category: 'Switch', hostname: 'FSL-BR-THA-AGG-R2-SW01', ipAddress: '10.4.21.16', description: 'Thane - Switch' },
  { id: 'tha-7', location: 'Thane', category: 'Switch', hostname: 'FSL-BR-THA-FRS-R1-SW01', ipAddress: '10.4.21.17', description: 'Thane - Switch' },
  { id: 'tha-8', location: 'Thane', category: 'PoE Switch', hostname: 'FSL-BR-THA-FRS-R1-POE-SW01', ipAddress: '10.4.21.18', description: 'Thane - PoE Switch' },
];
