"""init monitoring tables

Revision ID: 5a0a1a204664
Revises: 
Create Date: 2026-02-05 15:55:44.118584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0a1a204664'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_items', sa.Column('grafana_url', sa.String(), nullable=True))
    op.add_column('device_items', sa.Column('metric_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device_items', 'metric_groups', ['metric_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_items', type_='foreignkey')
    op.drop_column('device_items', 'metric_group_id')
    op.drop_column('device_items', 'grafana_url')
    # ### end Alembic commands ###
