"""alert_rules is_enabled boolean

Revision ID: f41cc240cf22
Revises: 5a0a1a204664
Create Date: 2026-02-05 17:50:33.362376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41cc240cf22'
down_revision: Union[str, Sequence[str], None] = '5a0a1a204664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'alert_rules',
        'is_enabled',
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using='is_enabled::boolean'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_rules', 'is_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
